version: "3"

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

services:
  web:
    build: ./docker/nginx
    container_name: "web"
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www
      - ./docker/logs:/var/www/logs
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    environment:
      TZ: Asia/Tokyo
    networks:
    - frontend
    - backend
    depends_on:
    - app

  app:
    build: ./docker/php
    container_name: "app"
    ports:
      - '3000:3000'
    tty: true
    volumes:
      - ./src:/var/www
      - ./docker/logs:/var/www/logs
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    environment:
      TZ: Asia/Tokyo
    networks:
    - frontend
    - backend